export const authors = [
  {
    name: "Napoleon Hill",
    image: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
    featuredBook: {
      title: "Pushing Clouds",
      author: "Napoleon Hill",
      category: "Business & Strategy",
      tag: "BEST SELLER",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
      originalPrice: 12.0,
      discountedPrice: 9.5,
      discountPercentage: 20,
      coverImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-GJ7YVJIOe6H1ioJXW00YhrgyQNBeBb.png",
      rating: 5,
    },
    books: [
      {
        title: "Think and Grow Rich",
        author: "Napoleon Hill",
        category: "Business & Strategy",
        description:
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        originalPrice: 15.25,
        discountedPrice: 9.5,
        discountPercentage: 15,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 5,
      },
      {
        title: "Pushing Clouds",
        author: "Jamet Sigh",
        category: "Business & Strategy",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        originalPrice: 12.0,
        discountedPrice: 5.7,
        discountPercentage: 20,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 4,
      },
      {
        title: "The Law of Success",
        author: "Napoleon Hill",
        category: "Business & Strategy",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        originalPrice: 18.99,
        discountedPrice: 12.5,
        discountPercentage: 10,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 4,
      },
      {
        title: "Outwitting the Devil",
        author: "Napoleon Hill",
        category: "Business & Strategy",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        originalPrice: 14.99,
        discountedPrice: 8.5,
        discountPercentage: 15,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 5,
      },
    ],
  },
  {
    name: "Jamet Sigh",
    image: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
    featuredBook: {
      title: "Think and Grow Rich",
      author: "Napoleon Hill",
      category: "Business & Strategy",
      tag: "BEST MANAGEMENT",
      description:
        "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal.",
      originalPrice: 15.25,
      discountedPrice: 17.2,
      discountPercentage: 15,
      coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
      rating: 5,
    },
    books: [
      {
        title: "Pushing Clouds",
        author: "Jamet Sigh",
        category: "Business & Strategy",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        originalPrice: 12.0,
        discountedPrice: 5.7,
        discountPercentage: 20,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 4,
      },
      {
        title: "Digital Transformation",
        author: "Jamet Sigh",
        category: "Technology",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        originalPrice: 14.99,
        discountedPrice: 8.99,
        discountPercentage: 15,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 5,
      },
      {
        title: "Think and Grow Rich",
        author: "Napoleon Hill",
        category: "Business & Strategy",
        description:
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
        originalPrice: 15.25,
        discountedPrice: 9.5,
        discountPercentage: 15,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 5,
      },
      {
        title: "Future of Work",
        author: "Jamet Sigh",
        category: "Business & Strategy",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        originalPrice: 16.5,
        discountedPrice: 10.99,
        discountPercentage: 10,
        coverImage: "https://1.bp.blogspot.com/-bn1T1J66g4U/Xln98cp7R_I/AAAAAAAAPG8/qLYQIUmHJ-QqTyw1aEGs3oSrlGoCASwoQCLcBGAsYHQ/s1600/Eiichiro%2BOda%2Bterbaru.jpg",
        rating: 4,
      },
    ],
  },
]

